### ISSUE TITLE
Extend comparison metadata

### ISSUE THREAD

**Issue by coldfix** [hibtc/madgui-old#47]
The comparison is currently restricted to envx, envy in a very special format. It should be generalized by providing additional metadata for:
- unit
- TWISS function
- column

e.g.

``` yaml
test-data:
- file: mirko.txt
  twiss-init: *id_twiss_init
  optic: optic_name
  sequence: sequence_name
  range: range_name
  columns:
  - s: mm           # column=0, name=s, unit=mm
  - none            # column=1, unknown/unhandled
  - envx: mm        # column=2, ...
  - envy: mm
```

or

``` yaml
  columns:   # or some other name, maybe twiss/data
    s:
      column: 0
      unit: mm
    envx:
      column: 1
      unit: mm
    envy:
      column: 2
      unit: mm
```

This format is more verbose, but provides more forward compatibility (in case more columns need to be added?). Furthermore, it has a more canonical in-memory representation.
