### ISSUE TITLE
Put constraints in a dict

### ISSUE THREAD

**Issue by coldfix** [hibtc/madgui-old#55]
Constraints should be put under the key of which function they are matching, e.g:

``` yaml
constraints:
  envx:
    elem1: value1
    elem2: value2
  envy:
    elem1: value3
    elem2: value4
```

This will also allow to use the plot_ax, update_ax events in DrawConstraints.
