### ISSUE TITLE
Define element selection rules (for matching) in config file

### ISSUE THREAD

**Issue by coldfix** [hibtc/madgui-old#61]
The elements can be defined in the config file, such that it is not necessary to change any real code, once this is implemented. The following example config describes the current selection rules for envelope matching:

``` yaml
matching:
  betx:
    quadrupole: k1
```
